name: trunk

on:
  push:
    branches:
      - main
      - release/*
    tags:
      - ciflow/trunk/*
  pull_request:
    paths:
      - .ci/docker/ci_commit_pins/pytorch.txt
      - .ci/scripts/**
  workflow_dispatch:

#concurrency:
#  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
#  cancel-in-progress: true

jobs:
  unittest-nxp-neutron:
    runs-on: ubuntu-22.04
    steps:
      - run: set -eux
#      - run: CONDA_ENV=$(conda env list --json | jq -r ".envs | .[-1]")
#      - run: conda activate "${CONDA_ENV}"
      - run: python --version
      - run: python -m venv venv
      - run: source venv/bin/activate
#      - run: # Build and install Executorch
      - name: Checkout code
        uses: actions/checkout@v4
      - run: ls ${{ github.workspace }}
      - run: PYTHON_EXECUTABLE=python  CMAKE_ARGS="-DEXECUTORCH_BUILD_NXP_NEUTRON=ON" .ci/scripts/setup-linux.sh --build-tool "cmake"
#      - run: # Run pytest
      - run: PYTHON_EXECUTABLE=python bash backends/nxp/run_unittests.sh
